/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class AddNative */

#ifndef _Included_AddNative
#define _Included_AddNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     AddNative
 * Method:    add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_AddNative_add
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
